### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [1]:
import pandas as pd

In [2]:
## creating the simple dataset
df = pd.DataFrame({
    'color': ['red','green','blue']
})

In [3]:
df.head(2)

   color
0    red
1  green

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
encoder = OneHotEncoder()

In [6]:
## perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [7]:
## make the dataframe
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoded_df.head()

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0

In [9]:
## for new data
encoder.transform([['blue']]).toarray()

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [10]:
## concating the data
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0

In [11]:
## another practies 
import seaborn as sns
df1 = sns.load_dataset('tips')

In [12]:
df1.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [14]:
## OneHotEncoding on the sex feature
sex_encoder = encoder.fit_transform(df1[['sex']]).toarray()

In [15]:
df1.shape

(244, 7)

In [16]:
sex_df = pd.DataFrame(sex_encoder, columns=encoder.get_feature_names_out())

In [17]:
sex_df.sample()

     sex_Female  sex_Male
224         0.0       1.0

In [18]:
df2 = pd.concat([df1,sex_df],axis=1)

In [19]:
df2.shape

(244, 9)

In [20]:
df2 = df2.drop(['sex'],axis=1)

In [21]:
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
df1[['smoker']].value_counts()

smoker
No        151
Yes        93
Name: count, dtype: int64

In [23]:
smoker_encoded = encoder.fit_transform(df2[['smoker']]).toarray()

In [24]:
df3 = pd.DataFrame(smoker_encoded,columns=encoder.get_feature_names_out())

In [25]:
df4 = pd.concat([df2,df3],axis=1)

In [26]:
df4.shape

(244, 10)

In [27]:
df4 = df4.drop(['smoker'],axis=1)

In [28]:
df4.head()

,total_bill,tip,day,time,size,sex_Female,sex_Male,smoker_No,smoker_Yes
0,16.99,1.01,Sun,Dinner,2,1.0,0.0,1.0,0.0
1,10.34,1.66,Sun,Dinner,3,0.0,1.0,1.0,0.0
2,21.01,3.50,Sun,Dinner,3,0.0,1.0,1.0,0.0
3,23.68,3.31,Sun,Dinner,2,0.0,1.0,1.0,0.0
4,24.59,3.61,Sun,Dinner,4,1.0,0.0,1.0,0.0

In [29]:
df4['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64