### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
le.fit_transform(df[['color']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2])

In [7]:
le.transform([['blue']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [8]:
le.transform([['red']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [9]:
le.transform([['green']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [20]:
## creating the data
df = pd.DataFrame({
    'size' : ['small','medium','large','small','large']
})

In [22]:
## ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
o_encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [23]:
df.head()

     size
0   small
1  medium
2   large
3   small
4   large

In [24]:
o_encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.]])

In [25]:
o_encoder.transform([['small']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [26]:
o_encoder.transform([['medium']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

In [27]:
o_encoder.transform([['large']])

D:\MachineLearning_Campusx\mlvenv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])